# Generated by Django 4.2 on 2024-09-18 20:41

import apps.utils.directory_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="IdDoctor", primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_column="FirstName", max_length=30),
                ),
                (
                    "last_name",
                    models.CharField(db_column="LastName", max_length=30),
                ),
                ("slug", models.SlugField(db_column="Slug")),
                (
                    "description",
                    models.TextField(
                        blank=True, db_column="Description", null=True
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        db_column="Photo",
                        null=True,
                        upload_to=apps.utils.directory_path.user_profile_pic_directory_path,
                        verbose_name="ProfilePic",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        db_column="Specialization",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        db_column="ContactEmail",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        db_column="ContactPhone",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(db_column="IsDeleted", default=False),
                ),
            ],
            options={
                "db_table": "Doctor",
            },
        ),
        migrations.CreateModel(
            name="DoctorStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="IdDoctorStatus",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=350),
                ),
            ],
            options={
                "db_table": "DoctorStatus",
            },
        ),
        migrations.CreateModel(
            name="DoctorUnavailableDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="IdDoctorUnavailableDate",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="Date")),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        db_column="Reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="Doctor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "DoctorUnavailableDate",
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="IdDoctorAvailability",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        db_column="DayOfWeek",
                    ),
                ),
                ("start_time", models.TimeField(db_column="StartTime")),
                ("end_time", models.TimeField(db_column="EndTime")),
                (
                    "is_active",
                    models.BooleanField(db_column="IsActive", default=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="Doctor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "DoctorAvailability",
            },
        ),
        migrations.AddField(
            model_name="doctor",
            name="doctor_status",
            field=models.ForeignKey(
                blank=True,
                db_column="DoctorStatus",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="doctors.doctorstatus",
            ),
        ),
    ]
