# Generated by Django 4.2 on 2024-09-18 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="slug",
        ),
    ]
