# Generated by Django 4.2 on 2024-09-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=100, null=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        db_column="PhoneNumber",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, db_column="Address", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Patient",
            },
        ),
    ]
