# Generated by Django 4.2 on 2024-09-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="IdAppointmentType",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=350),
                ),
            ],
            options={
                "db_table": "AppointmentType",
            },
        ),
    ]
