# Generated by Django 4.2 on 2024-09-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("appointments", "0002_appointmenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_column="Patient",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="patients.patient",
            ),
        ),
    ]
