# Generated by Django 4.2 on 2024-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OauthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("zoho", "Zoho")],
                        max_length=10,
                    ),
                ),
                ("access_token", models.CharField(max_length=512)),
                ("refresh_token", models.CharField(max_length=512)),
                (
                    "token_uri",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "client_id",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("scopes", models.TextField(blank=True, null=True)),
                (
                    "universe_domain",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "account",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("token_expiry", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
