# Generated by Django 4.2 on 2024-09-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField()),
                ("model", models.CharField(max_length=100)),
                ("temperature", models.FloatField(default=1.0)),
                ("top_p", models.FloatField(default=1.0)),
                (
                    "response_format",
                    models.CharField(default="auto", max_length=50),
                ),
                (
                    "tools",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "tool_resources",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_assistants",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
