# Generated by Django 4.2 on 2024-08-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistant_id",
                    models.CharField(max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField()),
                ("model", models.CharField(max_length=100)),
                ("temperature", models.FloatField(default=1.0)),
                ("top_p", models.FloatField(default=1.0)),
                (
                    "response_format",
                    models.CharField(default="auto", max_length=50),
                ),
                ("tools", models.JSONField(default=dict)),
                ("tool_resources", models.JSONField(default=dict)),
            ],
        ),
    ]
