# Generated by Django 4.2 on 2024-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="assistant_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
