# Generated by Django 4.2 on 2024-09-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("openai", "0002_alter_assistant_assistant_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_assistants",
                to="customers.customer",
            ),
        ),
    ]
