# Generated by Django 4.2 on 2024-09-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0004_alter_assistant_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="tool_resources",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="tools",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
