# Generated by Django 4.2 on 2024-08-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zohotoken",
            name="access_token",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="zohotoken",
            name="refresh_token",
            field=models.CharField(max_length=512),
        ),
    ]
