# Generated by Django 4.2 on 2024-08-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_oauthtoken_delete_zohotoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OauthToken",
        ),
    ]
