# Generated by Django 4.2 on 2024-09-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("openai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_customer_phone",
                    models.CharField(max_length=50, null=True),
                ),
                (
                    "thread_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_interaction",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "human_intervention_needed",
                    models.BooleanField(default=False),
                ),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openai.assistant",
                    ),
                ),
            ],
        ),
    ]
