# Generated by Django 4.2 on 2024-09-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_phone"),
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
